### ISSUE TITLE
Conditional Execution of SweetAlert Extension

### ISSUE THREAD

**Issue by Abdallah-Awwad** [nerkarso/directus-extensions#2]
Hello, thank you for developing this amazing extension! 
I have a question regarding its usage, 

Is it possible to trigger the SweetAlert extension based on specific conditions or events? such as item creation or being triggered by a flow or something? I'm particularly interested to use it to throw errors/warnings from a flow instead of the default one. 
<img alt="default error message from a flow" title="default error message from a flow" src="https://github.com/nerkarso/directus-extensions/assets/129249191/6c7a27bd-28d7-4328-a477-e00c8cd838b3" width="400"/>

What do you think? is that doable?

**Comment by plasebo** [comment]
Is it possible to invoke the sweetalert in the run script of flows?

**Comment by nerkarso** [comment]
> Hello, thank you for developing this amazing extension! I have a question regarding its usage,
> 
> Is it possible to trigger the SweetAlert extension based on specific conditions or events? such as item creation or being triggered by a flow or something? I'm particularly interested to use it to throw errors/warnings from a flow instead of the default one. <img alt="default error message from a flow" width="400" src="https://private-user-images.githubusercontent.com/129249191/338397173-6c7a27bd-28d7-4328-a477-e00c8cd838b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NDcyMDAsIm5iZiI6MTcyMDc0NjkwMCwicGF0aCI6Ii8xMjkyNDkxOTEvMzM4Mzk3MTczLTZjN2EyN2JkLTI4ZDctNDMyOC1hNDc3LWUwMGM4Y2Q4MzhiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMlQwMTE1MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01M2JmZTA1YWU1YWRlOTg5Mjc1MWY2NmJhMTdiNTMzMDRjNjJlYjAyNzcwOWRhMTRlMDQ3YmU0MzZkOTc1YmVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.K5RAleDy3F3EgidwfwoOcsQA_RQyqRYLC2DvXYXE8zA">
> 
> What do you think? is that doable?

No, this is currently not possible.

**Comment by nerkarso** [comment]
> Is it possible to invoke the sweetalert in the run script of flows?

Also not possible.
